# Generated by Django 3.0.5 on 2020-06-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groseriesapp', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='presentation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
