# Generated by Django 3.0.5 on 2020-06-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groseriesapp', '0003_auto_20200616_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(default='groseriesapp/images/default.png', upload_to='groseriesapp/images/'),
        ),
    ]
